const Colors = {
    darkGreen: '#afd1ab',
    lightGreen: "#f2fff2",
    white: "#FFFFFF",
    black: "#000000",
    gray: "#dedede",
    flatListBackground: "#FDFDFD",
    billsBackground: "#f0f7f7",
    greenButton: "#ced991",
    greenText: "#548E4E",
    buttonWhite: "#FDFDFD",
    borderColor: "#EAEAEA",
    radioButtonColor: '#F1F1F1',
    redText: "#8c5b54",
    contactColor: "#9C9C9C",
    keypadColor: "#E3EFE2"
};

const Constants = {
    center: "center",
    normal: "normal",
    bold: "bold",
    fiveHundred: "500",
    fourHundred: "400",
    sevenHundred: "700",
    hundredPerCent: "100%",
    dropdown: "dropdown",
    pickerLabel: 'Pick your network provider',
    row: "row",
    search: "Search",
    none: "none",
    viewAll: "view all",
    right: "right",
    showMore: "Show more",
    showLess: "Show less",
    billPayment: `Bill Payment`,
    goodAfternoon: "Good Afternoon,",
    tola: "Tola",
    walletBalance: `Wallet balance`,
    sendMoney: "Send Money",
    linkAccount: "Link Account",
    requestMoney: "Request Money",
    payBills: " Pay Bills",
    accountNumber: `Account Number - `,
    accountDigits: `1007886777`,
    recentTransactions: `Recent Transactions`,
    date: `Saturday, 11 February 2022`,
    spaceBetween: "space-between",
    absolute: "absolute",
    spaceEvenly: "space-evenly",
    flexEnd: "flex-end",
    networkProvider: `Network Provider`,
    category: `Category`,
    mobileTopUp: `Mobile Top-up`,
    dataBundle: `Data Bundle`,
    amount: `Amount`,
    enterAmount: `Enter Amount`,
    phoneNumber: `Phone Number`,
    enterPhoneNumber: "Enter Phone Number",
    numeric: `numeric`,
    phonePad: `phone-pad`,
    contacts: "Contacts",
    payWith: `Pay With`,
    purchase: `Purchase`,
    spaceAround: "space-around",
    mtn: "MTN",
    dialpadCaption: `Enter your transaction PIN to complete this payment`,
    wrap: 'wrap',
    logBox: 'A VirtualizedList contains a cell which itself contains more than one VirtualizedList '
};

export { Colors, Constants, }
